version: "2"

# To get DNS to work on your host / laptop, follow instructions:
#
# Ubuntu:
#   edit /etc/dhcp/dhclient.conf
#   add:
#      supersede domain-name "dev";
#      prepend domain-name-servers 127.0.0.1;
#

services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${NGINX_CONFIG}:/etc/nginx/conf.d/timeouts.conf
    network_mode: bridge

  devdns:
    image: jpillora/dnsmasq
    container_name: devdns
    ports:
      - "53:53/udp"
    volumes:
      - ${DNSMASQ_CONFIG}:/etc/dnsmasq.conf

  dockerdns:
    # See https://github.com/ruudud/devdns !
    image: ruudud/devdns
    container_name: dockerdns
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DNSMASQ_INTERNAL_CONFIG}:/etc/dnsmasq.conf
    environment:
      DNS_DOMAIN: "dev"
#    networks:
#      - bridge
    network_mode: bridge
    ports:
      - "54:53/udp"
#    ip: 172.17.254.254

  mysql:
    container_name: mysql
    image: mysql:5.6.26
    ports:
      - "3306:3306"
    network_mode: bridge # expose to other docker-compose networks.
#    networks:
#      - bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d
#      MYSQL_DATABASE: drupal
#      MYSQL_USER: drupal
#      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: mailhog.dev # This tell global proxy about this container.
      VIRTUAL_PORT: 8025
    network_mode: bridge # expose to other docker-compose networks.

#networks:
#  default:
#    external:
#      name: bridge

